version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Zipping LoginLambdaFunction.py"
      - zip function.zip LoginLambdaFunction.py

artifacts:
  files:
    - function.zip

post_build:
  commands:
    - echo "Deploying to Lambda function: LoginFunction"
    - aws lambda update-function-code --function-name LoginFunction --zip-file fileb://function.zip --region us-east-1
